# Generated by Django 6.0.5 on 2026-05-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='来源名称')),
                ('url', models.URLField(max_length=255, verbose_name='来源网址')),
                ('logo', models.URLField(blank=True, default='', max_length=255, verbose_name='Logo')),
                ('country', models.CharField(default='CN', max_length=50, verbose_name='国家')),
                ('language', models.CharField(default='zh', max_length=50, verbose_name='语言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻源',
                'verbose_name_plural': '新闻源',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(blank=True, default='', max_length=100, verbose_name='作者')),
                ('publish_time', models.DateTimeField(db_index=True, verbose_name='发布时间')),
                ('url', models.URLField(db_index=True, max_length=500, unique=True, verbose_name='原文链接')),
                ('cover_image', models.URLField(blank=True, default='', max_length=500, verbose_name='封面图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='分类')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.source', verbose_name='来源')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-publish_time'],
                'indexes': [models.Index(fields=['-publish_time'], name='api_news_publish_9fa780_idx'), models.Index(fields=['title'], name='api_news_title_4772e8_idx')],
            },
        ),
    ]
