# Generated by Django 6.0.5 on 2026-05-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.news', verbose_name='关联主新闻'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_hash',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='标题哈希'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('news', '新闻媒体'), ('aggregator', '聚合平台'), ('discussion', '讨论社区')], default='news', max_length=20, verbose_name='类型'),
        ),
    ]
