# Generated by Django 6.0.5 on 2026-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_news_related_to_news_title_hash_source_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_zh',
            field=models.TextField(blank=True, default='', verbose_name='中文内容'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_zh',
            field=models.TextField(blank=True, default='', verbose_name='中文标题'),
        ),
    ]
