# Generated by Django 6.0.5 on 2026-05-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_news_content_zh_news_title_zh'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='last_translation_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后翻译时间'),
        ),
        migrations.AddField(
            model_name='news',
            name='translation_error',
            field=models.TextField(blank=True, default='', verbose_name='翻译错误信息'),
        ),
        migrations.AddField(
            model_name='news',
            name='translation_retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='重试次数'),
        ),
        migrations.AddField(
            model_name='news',
            name='translation_status',
            field=models.CharField(choices=[('pending', '等待翻译'), ('translating', '翻译中'), ('success', '翻译成功'), ('failed', '翻译失败'), ('network_error', '网络错误')], db_index=True, default='pending', max_length=20, verbose_name='翻译状态'),
        ),
    ]
