# Generated by Django 6.0.5 on 2026-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_translation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_content',
            field=models.TextField(blank=True, default='', verbose_name='完整原文(Markdown)'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_content_fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='原文获取时间'),
        ),
    ]
