# Generated by Django 6.0.5 on 2026-05-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_full_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_content_zh',
            field=models.TextField(blank=True, default='', verbose_name='完整原文(中文)'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_content_zh_fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='中文翻译时间'),
        ),
    ]
