# Generated by Django 6.0.5 on 2026-05-31 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_full_content_zh'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(blank=True, default=list, verbose_name='对话记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='api.news')),
            ],
            options={
                'verbose_name': '对话会话',
                'verbose_name_plural': '对话会话',
            },
        ),
    ]
