# Generated by Django 6.0.5 on 2026-05-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='suggested_questions',
            field=models.JSONField(blank=True, default=list, verbose_name='AI 推荐问题'),
        ),
        migrations.AddField(
            model_name='news',
            name='suggested_questions_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='推荐问题生成时间'),
        ),
    ]
