# Generated by Django 6.0.5 on 2026-05-31 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='api.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '屏蔽',
                'verbose_name_plural': '屏蔽',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'news'), name='unique_user_blocked_news')],
            },
        ),
    ]
