# Generated by Django 6.0.5 on 2026-06-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_blocked_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_content_fetch_error',
            field=models.TextField(blank=True, default='', verbose_name='全文抓取错误信息'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_content_fetch_provider',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='全文抓取 Provider'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_content_fetch_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('success', 'Success'), ('failed', 'Failed'), ('network_error', 'Network Error'), ('validation_failed', 'Validation Failed')], db_index=True, default='pending', max_length=32, verbose_name='全文抓取状态'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_content_quality_score',
            field=models.FloatField(blank=True, null=True, verbose_name='全文质量分'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_content_retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='全文抓取重试次数'),
        ),
        migrations.AddField(
            model_name='news',
            name='last_full_content_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后全文抓取时间'),
        ),
    ]
