# Generated by Django 6.0.5 on 2026-06-01 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_news_full_content_fetch_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, verbose_name='对比运行 ID')),
                ('url', models.URLField(db_index=True, max_length=500, verbose_name='原文链接')),
                ('expected_title', models.CharField(blank=True, default='', max_length=500, verbose_name='期望标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('provider', models.CharField(db_index=True, max_length=64, verbose_name='Provider')),
                ('ok', models.BooleanField(db_index=True, default=False, verbose_name='是否成功')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='抓取标题')),
                ('canonical_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Canonical URL')),
                ('markdown', models.TextField(blank=True, default='', verbose_name='Provider 返回 Markdown')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='质量分')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('validation_reasons', models.JSONField(blank=True, default=list, verbose_name='校验失败原因')),
                ('content_length', models.PositiveIntegerField(default=0, verbose_name='内容长度')),
                ('extractor', models.CharField(blank=True, default='', max_length=128, verbose_name='Extractor')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Provider 元数据')),
                ('elapsed_ms', models.PositiveIntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_comparisons', to='api.news', verbose_name='新闻')),
            ],
            options={
                'verbose_name': 'Provider 对比结果',
                'verbose_name_plural': 'Provider 对比结果',
                'ordering': ['-created_at', 'provider'],
                'indexes': [models.Index(fields=['run_id', 'provider'], name='api_provide_run_id_d37e7f_idx'), models.Index(fields=['url', '-created_at'], name='api_provide_url_2997c8_idx')],
            },
        ),
    ]
