# Generated by Django 6.0.5 on 2026-06-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_provider_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='full_content_backfill_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scrapy 回填时间'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_content_backfill_source',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Scrapy 回填来源'),
        ),
    ]
