# Generated by Django 6.0.5 on 2026-06-04 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_news_full_content_backfill_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='会话标题')),
                ('messages', models.JSONField(blank=True, default=list, verbose_name='对话记录')),
                ('is_archived', models.BooleanField(default=False, verbose_name='已归档')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '研究会话',
                'verbose_name_plural': '研究会话',
                'ordering': ['-updated_at'],
            },
        ),
    ]
