# Generated by Django 6.0.5 on 2026-06-05 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_researchsession_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSearchResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=50, verbose_name='工具名称')),
                ('query', models.CharField(blank=True, default='', max_length=500, verbose_name='搜索查询')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='结果数据')),
                ('result_type', models.CharField(db_index=True, max_length=20, verbose_name='结果类型')),
                ('source', models.CharField(blank=True, default='', max_length=100, verbose_name='来源')),
                ('title', models.CharField(blank=True, default='', max_length=500, verbose_name='标题')),
                ('url', models.URLField(blank=True, default='', max_length=2000, verbose_name='链接')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='结果数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='api.researchsession', verbose_name='研究会话')),
            ],
            options={
                'verbose_name': '搜索结果',
                'verbose_name_plural': '搜索结果',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'result_type'], name='idx_result_session_type'), models.Index(fields=['session', 'created_at'], name='idx_result_session_created')],
            },
        ),
    ]
