# Generated by Django 6.1 on 2026-10-08 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cancel_attempts_with_legacy_selection_snapshots(apps, schema_editor):
    AuthAttempt = apps.get_model('api', 'ChatGPTAuthAttempt')
    AuthAttempt.objects.filter(
        status__in=['pending', 'authorizing', 'processing'],
    ).update(
        status='cancelled',
        status_message='升级后请重新开始授权。',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_chatgpt_auth_binding_and_selection'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPTSubscriptionSelection',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chatgpt_subscription_selection', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ChatGPT 订阅选择状态',
                'verbose_name_plural': 'ChatGPT 订阅选择状态',
            },
        ),
        migrations.RunPython(
            cancel_attempts_with_legacy_selection_snapshots,
            migrations.RunPython.noop,
        ),
    ]
