# Generated by Django 6.1 on 2026-10-09 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_subscription_selection_generation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTarget',
            fields=[
                ('spider_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('last_status', models.CharField(blank=True, default='', max_length=32)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_items', models.PositiveIntegerField(default=0)),
                ('last_responses', models.PositiveIntegerField(default=0)),
                ('last_errors', models.PositiveIntegerField(default=0)),
                ('last_safe_error', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': '爬虫来源',
                'verbose_name_plural': '爬虫来源',
                'ordering': ['sort_order', 'spider_name'],
            },
        ),
        migrations.CreateModel(
            name='CrawlBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('startup', 'Startup'), ('manual', 'Manual'), ('retry', 'Retry')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('succeeded', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('cancelled', models.PositiveIntegerField(default=0)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_crawl_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '抓取批次',
                'verbose_name_plural': '抓取批次',
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('scheduler_enabled', models.BooleanField(default=True)),
                ('interval_seconds', models.PositiveIntegerField(default=3600)),
                ('run_on_worker_start', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('worker_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('worker_instance_id', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawler_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '爬虫调度设置',
                'verbose_name_plural': '爬虫调度设置',
            },
        ),
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancel_requested', 'Cancel requested'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=24)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('items', models.PositiveIntegerField(default=0)),
                ('responses', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('http_statuses', models.JSONField(blank=True, default=dict)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('safe_error', models.CharField(blank=True, default='', max_length=500)),
                ('log_path', models.CharField(blank=True, default='', max_length=500)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.crawlbatch')),
                ('cancel_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_crawl_runs', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_crawl_runs', to=settings.AUTH_USER_MODEL)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='api.crawlrun')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='api.crawlertarget')),
            ],
            options={
                'verbose_name': '抓取任务',
                'verbose_name_plural': '抓取任务',
                'ordering': ['-queued_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running', 'cancel_requested'])), fields=('target',), name='one_active_crawl_run_per_target')],
            },
        ),
    ]
