# Generated by Django 6.1.2 on 2026-10-09 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_crawler_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndexSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('interval_seconds', models.PositiveIntegerField(default=300)),
                ('batch_size', models.PositiveIntegerField(default=100)),
                ('active_collection', models.CharField(default='news_embeddings', max_length=128)),
                ('model_name', models.CharField(default='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2', max_length=255)),
                ('schema_version', models.CharField(default='news-v1', max_length=64)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('worker_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('worker_instance_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_index_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '语义索引设置',
                'verbose_name_plural': '语义索引设置',
            },
        ),
        migrations.CreateModel(
            name='SearchIndexRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('startup', 'Startup'), ('scheduled', 'Scheduled'), ('crawl_batch', 'Crawl batch'), ('manual', 'Manual'), ('recovery', 'Recovery')], max_length=20)),
                ('mode', models.CharField(choices=[('sync', 'Sync'), ('rebuild', 'Rebuild')], default='sync', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('cancel_requested', 'Cancel requested'), ('cancelled', 'Cancelled'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=24)),
                ('active_slot', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('collection_name', models.CharField(blank=True, default='', max_length=128)),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('schema_version', models.CharField(blank=True, default='', max_length=64)),
                ('news_count', models.PositiveIntegerField(default=0)),
                ('vector_count_before', models.PositiveIntegerField(default=0)),
                ('vector_count_after', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('changed_count', models.PositiveIntegerField(default=0)),
                ('orphaned_count', models.PositiveIntegerField(default=0)),
                ('upserted_count', models.PositiveIntegerField(default=0)),
                ('deleted_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('safe_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('safe_error_message', models.CharField(blank=True, default='', max_length=500)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_search_index_runs', to=settings.AUTH_USER_MODEL)),
                ('crawl_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_index_runs', to='api.crawlbatch')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_search_index_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '语义索引任务',
                'verbose_name_plural': '语义索引任务',
                'ordering': ['-queued_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running', 'cancel_requested'])), fields=('active_slot',), name='one_active_search_index_run'), models.UniqueConstraint(condition=models.Q(('crawl_batch__isnull', False)), fields=('crawl_batch',), name='one_search_index_run_per_crawl_batch')],
            },
        ),
    ]
