# Generated by Django 6.1.2 on 2026-10-09 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_chatgpt_connection_id_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(max_length=64)),
                ('target_language', models.CharField(default='zh-CN', max_length=16)),
                ('translation_version', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('provider', models.CharField(max_length=32)),
                ('model_slug', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_translations', to='api.news')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('news', 'source_hash', 'target_language', 'translation_version'), name='unique_shared_article_translation')],
            },
        ),
        migrations.CreateModel(
            name='SharedArticleTranslationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(max_length=64)),
                ('target_language', models.CharField(default='zh-CN', max_length=16)),
                ('translation_version', models.CharField(max_length=32)),
                ('status', models.CharField(default='idle', max_length=16)),
                ('lease_token', models.UUIDField(default=uuid.uuid4)),
                ('expires_at', models.DateTimeField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_translation_tasks', to='api.news')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('news', 'source_hash', 'target_language', 'translation_version'), name='unique_shared_article_task')],
            },
        ),
    ]
