"""
Django settings for newsaggregator project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from .runtime_config import parse_runtime_config, resolve_django_environment

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Select the mode from the process environment before considering any dotenv
# file. In particular, a production process never reads a workspace .env.
DJANGO_ENV = resolve_django_environment(os.environ)
os.environ.setdefault('DJANGO_ENV', DJANGO_ENV)
if DJANGO_ENV == 'development':
    try:
        from dotenv import load_dotenv
        for _candidate in (BASE_DIR.parent / '.env', BASE_DIR / '.env'):
            if _candidate.exists():
                load_dotenv(_candidate, override=False)
    except ImportError:
        pass

_RUNTIME_CONFIG = parse_runtime_config(os.environ, environment=DJANGO_ENV)


def _env(name: str, default: str = '') -> str:
    return os.environ.get(name, default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Production requires an explicitly configured stable key. Only development
# retains the per-process fallback used by the local quick start.
SECRET_KEY = _RUNTIME_CONFIG.secret_key

# Subscription tokens need a stable key across process restarts. In local mode
# this defaults only to the explicitly configured stable Django secret.
CHATGPT_TOKEN_ENCRYPTION_KEY = _env('CHATGPT_TOKEN_ENCRYPTION_KEY') or _env('DJANGO_SECRET_KEY')
CHATGPT_AGENT_NAME_HINT = _env('CHATGPT_AGENT_NAME_HINT', 'News Aggregator')
CHATGPT_DEPLOYMENT_INSTANCE_ID = _env('CHATGPT_DEPLOYMENT_INSTANCE_ID')
CHATGPT_DEPLOYMENT_INSTANCE_FILE = Path(
    _env('CHATGPT_DEPLOYMENT_INSTANCE_FILE') or BASE_DIR / '.runtime' / 'chatgpt-deployment-id'
)

DEBUG = _RUNTIME_CONFIG.debug
ALLOWED_HOSTS = list(_RUNTIME_CONFIG.allowed_hosts)
PUBLIC_SITE_MODE = _RUNTIME_CONFIG.public_site_mode
PUBLIC_SIGNUP_ENABLED = _RUNTIME_CONFIG.public_signup_enabled
PUBLIC_AI_ENABLED = _RUNTIME_CONFIG.public_ai_enabled
CHATGPT_PLAN_USAGE_ENABLED = _RUNTIME_CONFIG.chatgpt_plan_usage_enabled
CHATGPT_AUTH_MODE = _RUNTIME_CONFIG.chatgpt_auth_mode
WAITRESS_TRUSTED_PROXY = _RUNTIME_CONFIG.waitress_trusted_proxy


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'api.public_policy.PublicPolicyMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'newsaggregator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newsaggregator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # WAL mode: concurrent reads + faster writes, critical for mobile/eMMC
        # storage where fsync latency is high and Scrapy pipeline writes
        # frequently during crawl.
        'OPTIONS': {
            'timeout': 30,
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA cache_size=-2000; PRAGMA foreign_keys=ON;',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR.parent / 'frontend' / 'dist' / 'assets',
]
FRONTEND_DIR = BASE_DIR.parent / 'frontend' / 'dist'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

CORS_ALLOW_ALL_ORIGINS = DJANGO_ENV != 'production'
CORS_ALLOW_CREDENTIALS = DJANGO_ENV != 'production'

# CSRF & Session — SPA served from same origin (Django :9527) or Vite dev proxy
CSRF_TRUSTED_ORIGINS = list(_RUNTIME_CONFIG.csrf_trusted_origins)
CHATGPT_HANDOFF_ALLOWED_ORIGINS = ['http://127.0.0.1:5173', 'http://127.0.0.1:9527']
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = DJANGO_ENV == 'production'
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # SPA needs to read it for X-CSRFToken header
CSRF_COOKIE_SECURE = DJANGO_ENV == 'production'
CSRF_COOKIE_DOMAIN = None

# Only the precise internal health paths bypass the HTTPS redirect so local
# container probes can use HTTP without weakening the rest of the API.
SECURE_SSL_REDIRECT = DJANGO_ENV == 'production'
SECURE_REDIRECT_EXEMPT = [r'^api/health/(live|ready)/$']
SECURE_PROXY_SSL_HEADER = None
SECURE_HSTS_SECONDS = 3600 if DJANGO_ENV == 'production' else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Auto-fetch full content daemon settings (override via .env)
# How often to poll for new pending articles (seconds)
AUTO_FETCH_INTERVAL = int(_env('AUTO_FETCH_INTERVAL', '300'))
# Max articles to process per batch
AUTO_FETCH_BATCH = int(_env('AUTO_FETCH_BATCH', '10'))
# Seconds to sleep between individual fetch requests (anti-bot throttle)
AUTO_FETCH_THROTTLE = float(_env('AUTO_FETCH_THROTTLE', '2.0'))

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {'level': 'WARNING', 'handlers': ['console'], 'propagate': False},
    },
}
